version: '2'
services:
    dotty1-app:
        image: dotty1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dotty1-mysql:3306/dotty1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dotty1-elasticsearch:9300
        ports:
            - 8080:8080
    dotty1-mysql:
        extends:
            file: mysql.yml
            service: dotty1-mysql
    dotty1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dotty1-elasticsearch
